### ISSUE TITLE
Publish docker images to Docker Hub registry

### ISSUE THREAD

**Issue by buckyroberts** [thenewboston-developers/Core#115]
TODO:
- [DONE] Split Dockerfile into 2 files
- [DONE] Setup Docker Hub repositories
- [DONE] Setup Docker Hub tests
- [DONE] Switch to deployment from Docker Hub

**Comment by dmugtasimov** [comment]
Splitted Dockerfile: https://github.com/thenewboston-developers/Core/pull/119

**Comment by dmugtasimov** [comment]
Docker Hub setup: https://github.com/thenewboston-developers/Core/pull/120

**Comment by dmugtasimov** [comment]
Unittests for Docker Hub: https://github.com/thenewboston-developers/Core/pull/121

**Comment by dmugtasimov** [comment]
Partial switching to Docker Hub: https://github.com/thenewboston-developers/Core/pull/123

**Comment by dmugtasimov** [comment]
Remaining switching: https://github.com/thenewboston-developers/Core/pull/124

**Comment by dmugtasimov** [comment]
@buckyroberts Done.

See updated INSTALL.production.rst

Briefly:
- End-users can deploy from Docker Hub public repositories (not need for authentication)
- We still deploy from GitHub registry to thenewboston.network, because we need to trigger deployment after image built is ready (while Docker Hub may delay builds and overall there is no synchronization between GitHub actions and Docker Hub image builds)
- End-users can still deploy from GitHub registry if they want to, but it is not recommended, because it is more complicated because of GitHub registry authentication
